In [10]:
import pandas as pd

# Need to read all files ...
# NC FIPS is 37 !!!

# # # # #
fips = '37001'
# # # # #

import os

ddir = 'raw_data/covidhub-trained_ensemble-2021/'

df_list = []
for fname in os.listdir(ddir):
    if fname.endswith('.csv'):
        fpath = os.path.join(ddir, fname)
        df = pd.read_csv(fpath)
        df = df[df.location==fips]
        df = df[df.type=='point']
        df = df[df.target=='1 wk ahead inc death']
#         df = df[df.target.isin(['1 wk ahead cum death',
#                         '2 wk ahead cum death',
#                         '3 wk ahead cum death',
#                         '4 wk ahead cum death'])]
        df_list.append(df)
#         print(fname, len(df))

bigdf = pd.concat(df_list)
# bigdf.to_csv('processed_data/nc_state_projections.csv',index=False)
# bigdf

In [14]:
bigdf.target.unique()

array(['1 wk ahead inc case', '2 wk ahead inc case',
       '3 wk ahead inc case', '4 wk ahead inc case'], dtype=object)

In [16]:
bigdf[:20]

,forecast_date,target,target_end_date,location,type,quantile,value
100809,2021-02-01,1 wk ahead inc case,2021-02-06,37001,point,NaN,552
103951,2021-02-01,2 wk ahead inc case,2021-02-13,37001,point,NaN,536
107093,2021-02-01,3 wk ahead inc case,2021-02-20,37001,point,NaN,493
110235,2021-02-01,4 wk ahead inc case,2021-02-27,37001,point,NaN,423
100809,2021-02-08,1 wk ahead inc case,2021-02-13,37001,point,NaN,586
103951,2021-02-08,2 wk ahead inc case,2021-02-20,37001,point,NaN,550
107093,2021-02-08,3 wk ahead inc case,2021-02-27,37001,point,NaN,531
110235,2021-02-08,4 wk ahead inc case,2021-03-06,37001,point,NaN,541
100713,2021-02-15,1 wk ahead inc case,2021-02-20,37001,point,NaN,830
103855,2021-02-15,2 wk ahead inc case,2021-02-27,37001,point,NaN,911
106997,2021-02-15,3 wk ahead inc case,2021-03-06,37001,point,NaN,944
110139,2021-02-15,4 wk ahead inc case,2021-03-13,37001,point,NaN,1000
100809,2021-02-22,1 wk ahead inc case,2021-02-27,37001,point,NaN,274
103951,2021-02-22,2 wk ahead inc case,2021-03-06,37001,point,NaN,245
107093,2021-02-22,3 wk ahead inc case,2021-03-13,37001,point,NaN,213
110235,2021-02-22,4 wk ahead inc case,2021-03-20,37001,point,NaN,189
100809,2021-03-01,1 wk ahead inc case,2021-03-06,37001,point,NaN,222
103951,2021-03-01,2 wk ahead inc case,2021-03-13,37001,point,NaN,231
107093,2021-03-01,3 wk ahead inc case,2021-03-20,37001,point,NaN,217
110235,2021-03-01,4 wk ahead inc case,2021-03-27,37001,point,NaN,211

## <font color=magenta> ^ These are cases, NOT deaths. I'm not trying to predict these numbers so (I think) I can ignore them for now ...