In [1]:
%%capture
%load_ext autoreload
%autoreload 2
from setup_nb_env import *

from epsampling.utils import load_csv
# pd.set_option('display.float_format', lambda x: '%.3f' % x)
from epsampling.utils import drop_sers_with_nans

DATA_DIR = '/work/users/k/4/k4thryn/Repos/EpSampling/data/'
DT = datetime.today().strftime('%Y%m%d-%H%M%S')

In [ ]:
# timestamp = '20240928-145111'

# fpath = os.path.join(DATA_DIR,'processed',f'formatted_COVIDhub-ensemble_{timestamp}.csv')
# df_hub = pd.read_csv(fpath)
# df_hub = fips_to_str(df_hub)
# df_hub['State_fips'] = df_hub.State_fips.astype('str')
# df_hub['State_fips'] = df_hub.State_fips.apply(lambda x: x.zfill(2))

In [ ]:
#####################################################
## NYT TRUE COUNTY DEATHS ###########################
#####################################################

# fpath = os.path.join(DATA_DIR,'raw','nytimes','us-counties.csv')
# df = pd.read_csv(fpath)

# ## check for rows with nans. 
# # display(df)
# df = drop_sers_with_nans(df, from_axis='rows')
# # df.reset_index(drop=True, inplace=True)
# # display(df)

# ## REFORMAT dataframe ...
# ## capitalize cols.
# df.columns = df.columns.str.capitalize()
# df

In [24]:
timestamp = '20240928-145111'

# fpath = os.path.join(DATA_DIR,'processed',f'formatted_state_fips_{timestamp}.csv')
# df_fips = pd.read_csv(fpath)

# fpath = os.path.join(DATA_DIR,'processed',f'formatted_COVIDhub-ensemble_{timestamp}.csv')
# df_hub = pd.read_csv(fpath)
# df_hub = fips_to_str(df_hub)
# df_hub['State_fips'] = df_hub.State_fips.astype('str')
# df_hub['State_fips'] = df_hub.State_fips.apply(lambda x: x.zfill(2))


fpath = os.path.join(DATA_DIR,'processed',f'formatted_nytimes-us-counties_{timestamp}.csv')
df_nyt = pd.read_csv(fpath)
# df_nyt = fips_to_str(df_nyt)
df_nyt

         Fips        Date  True_cum_deaths
0        1001  2020-06-13              6.0
1        1003  2020-06-13              9.0
2        1005  2020-06-13              1.0
3        1007  2020-06-13              1.0
4        1009  2020-06-13              1.0
...       ...         ...              ...
313231  56037  2022-05-07            126.0
313232  56039  2022-05-07             16.0
313233  56041  2022-05-07             39.0
313234  56043  2022-05-07             44.0
313235  56045  2022-05-07             18.0

[313236 rows x 3 columns]

In [25]:
df_nyt = df_nyt.sort_values(['Fips','Date'])

dffs = []
for fips in tqdm(df_nyt.Fips.unique()):
    
    dff = df[df.Fips==fips]
    dff.reset_index(inplace=True, drop=True)
    
    inc_deathss = []
    for i in range(len(dff)):
        if i==0:
            inc_deaths = np.nan
        else:            
            inc_deaths = dff.True_cum_deaths.values[i] - dff.True_cum_deaths.values[i-1]
        inc_deathss.append(inc_deaths)
            
    dff['True_inc_deaths'] = inc_deathss
#     break
    
    dffs.append(dff)

100%|██████████| 3141/3141 [00:07<00:00, 430.12it/s]

In [29]:
df = pd.concat(dffs)
df.dropna(inplace=True)
df

     Fips        Date  True_cum_deaths  True_inc_deaths
1    1001  2020-06-27             12.0              3.0
2    1001  2020-07-04             13.0              1.0
3    1001  2020-07-11             15.0              2.0
4    1001  2020-07-18             21.0              6.0
5    1001  2020-07-25             21.0              0.0
..    ...         ...              ...              ...
94  78030  2022-04-09             59.0              0.0
95  78030  2022-04-16             59.0              0.0
96  78030  2022-04-23             59.0              0.0
97  78030  2022-04-30             59.0              0.0
98  78030  2022-05-07             59.0              0.0

[306954 rows x 4 columns]

In [32]:
df.min()

Fips                     1001
Date               2020-06-27
True_cum_deaths           0.0
True_inc_deaths        -792.0
dtype: object

In [33]:
df.True_inc_deaths.values.min()

-792.0

In [34]:
df[df.True_inc_deaths==-792]

     Fips        Date  True_cum_deaths  True_inc_deaths
91  25017  2022-03-19           3934.0           -792.0

In [35]:
df[df.Fips==25017]

     Fips        Date  True_cum_deaths  True_inc_deaths
1   25017  2020-06-27           1849.0             48.0
2   25017  2020-07-04           1877.0             28.0
3   25017  2020-07-11           1913.0             36.0
4   25017  2020-07-18           1944.0             31.0
5   25017  2020-07-25           1955.0             11.0
6   25017  2020-08-01           1983.0             28.0
7   25017  2020-08-08           2002.0             19.0
8   25017  2020-08-15           2006.0              4.0
9   25017  2020-08-22           2043.0             37.0
10  25017  2020-08-29           2064.0             21.0
11  25017  2020-09-05           2082.0             18.0
12  25017  2020-09-12           2102.0             20.0
13  25017  2020-09-19           2120.0             18.0
14  25017  2020-09-26           2143.0             23.0
15  25017  2020-10-03           2166.0             23.0
16  25017  2020-10-10           2186.0             20.0
17  25017  2020-10-17           2219.0             33.0
18  25017  2020-10-24           2245.0             26.0
19  25017  2020-10-31           2281.0             36.0
20  25017  2020-11-07           2314.0             33.0
21  25017  2020-11-14           2351.0             37.0
22  25017  2020-11-21           2379.0             28.0
23  25017  2020-11-28           2409.0             30.0
24  25017  2020-12-05           2455.0             46.0
25  25017  2020-12-12           2522.0             67.0
26  25017  2020-12-19           2582.0             60.0
27  25017  2020-12-26           2658.0             76.0
28  25017  2021-01-02           2740.0             82.0
29  25017  2021-01-09           2837.0             97.0
30  25017  2021-01-16           2939.0            102.0
31  25017  2021-01-23           3031.0             92.0
32  25017  2021-01-30           3114.0             83.0
33  25017  2021-02-06           3202.0             88.0
34  25017  2021-02-13           3295.0             93.0
35  25017  2021-02-20           3371.0             76.0
36  25017  2021-02-27           3429.0             58.0
37  25017  2021-03-06           3482.0             53.0
38  25017  2021-03-13           3530.0             48.0
39  25017  2021-03-20           3571.0             41.0
40  25017  2021-03-27           3624.0             53.0
41  25017  2021-04-03           3666.0             42.0
42  25017  2021-04-10           3685.0             19.0
43  25017  2021-04-17           3695.0             10.0
44  25017  2021-04-24           3709.0             14.0
45  25017  2021-05-01           3721.0             12.0
46  25017  2021-05-08           3732.0             11.0
47  25017  2021-05-15           3739.0              7.0
48  25017  2021-05-22           3751.0             12.0
49  25017  2021-05-29           3757.0              6.0
50  25017  2021-06-05           3764.0              7.0
51  25017  2021-06-12           3770.0              6.0
52  25017  2021-06-19           3772.0              2.0
53  25017  2021-06-26           3777.0              5.0
54  25017  2021-07-03           3781.0              4.0
55  25017  2021-07-10           3782.0              1.0
56  25017  2021-07-17           3786.0              4.0
57  25017  2021-07-24           3791.0              5.0
58  25017  2021-07-31           3794.0              3.0
59  25017  2021-08-07           3797.0              3.0
60  25017  2021-08-14           3801.0              4.0
61  25017  2021-08-21           3803.0              2.0
62  25017  2021-08-28           3810.0              7.0
63  25017  2021-09-04           3818.0              8.0
64  25017  2021-09-11           3830.0             12.0
65  25017  2021-09-18           3844.0             14.0
66  25017  2021-09-25           3857.0             13.0
67  25017  2021-10-02           3873.0             16.0
68  25017  2021-10-09           3889.0             16.0
69  25017  2021-10-16           3900.0             11.0
70  25017  2021-10-23           3913.0             13.0
71  25017  2021-10-30           3925.0             12.0
72  25017  2021-11-06           3935.0             10.0
73  25017  2021-11-13           3944.0              9.0
74  25017  2021-11-20           3959.0             15.0
75  25017  2021-11-27           3973.0             14.0
76  25017  2021-12-04           3998.0             25.0
77  25017  2021-12-11           4022.0             24.0
78  25017  2021-12-18           4057.0             35.0
79  25017  2021-12-25           4094.0             37.0
80  25017  2022-01-01           4129.0             35.0
81  25017  2022-01-08           4166.0             37.0
82  25017  2022-01-15           4228.0             62.0
83  25017  2022-01-22           4323.0             95.0
84  25017  2022-01-29           4421.0             98.0
85  25017  2022-02-05           4505.0             84.0
86  25017  2022-02-12           4572.0             67.0
87  25017  2022-02-19           4615.0             43.0
88  25017  2022-02-26           4652.0             37.0
89  25017  2022-03-05           4693.0             41.0
90  25017  2022-03-12           4726.0             33.0
91  25017  2022-03-19           3934.0           -792.0
92  25017  2022-03-26           3942.0              8.0
93  25017  2022-04-02           3951.0              9.0
94  25017  2022-04-09           3955.0              4.0
95  25017  2022-04-16           3961.0              6.0
96  25017  2022-04-23           3970.0              9.0
97  25017  2022-04-30           3976.0              6.0
98  25017  2022-05-07           3988.0             12.0

In [40]:
df[df.True_inc_deaths==-377]

     Fips        Date  True_cum_deaths  True_inc_deaths
91  25021  2022-03-19           1865.0           -377.0

In [41]:
df[df.Fips==25021]

     Fips        Date  True_cum_deaths  True_inc_deaths
1   25021  2020-06-27            927.0             19.0
2   25021  2020-07-04            937.0             10.0
3   25021  2020-07-11            957.0             20.0
4   25021  2020-07-18            966.0              9.0
5   25021  2020-07-25            976.0             10.0
6   25021  2020-08-01            986.0             10.0
7   25021  2020-08-08            997.0             11.0
8   25021  2020-08-15            997.0              0.0
9   25021  2020-08-22           1004.0              7.0
10  25021  2020-08-29           1016.0             12.0
11  25021  2020-09-05           1022.0              6.0
12  25021  2020-09-12           1030.0              8.0
13  25021  2020-09-19           1046.0             16.0
14  25021  2020-09-26           1058.0             12.0
15  25021  2020-10-03           1071.0             13.0
16  25021  2020-10-10           1080.0              9.0
17  25021  2020-10-17           1090.0             10.0
18  25021  2020-10-24           1101.0             11.0
19  25021  2020-10-31           1111.0             10.0
20  25021  2020-11-07           1125.0             14.0
21  25021  2020-11-14           1147.0             22.0
22  25021  2020-11-21           1157.0             10.0
23  25021  2020-11-28           1176.0             19.0
24  25021  2020-12-05           1193.0             17.0
25  25021  2020-12-12           1212.0             19.0
26  25021  2020-12-19           1243.0             31.0
27  25021  2020-12-26           1266.0             23.0
28  25021  2021-01-02           1307.0             41.0
29  25021  2021-01-09           1356.0             49.0
30  25021  2021-01-16           1388.0             32.0
31  25021  2021-01-23           1432.0             44.0
32  25021  2021-01-30           1474.0             42.0
33  25021  2021-02-06           1509.0             35.0
34  25021  2021-02-13           1559.0             50.0
35  25021  2021-02-20           1593.0             34.0
36  25021  2021-02-27           1613.0             20.0
37  25021  2021-03-06           1649.0             36.0
38  25021  2021-03-13           1665.0             16.0
39  25021  2021-03-20           1692.0             27.0
40  25021  2021-03-27           1714.0             22.0
41  25021  2021-04-03           1736.0             22.0
42  25021  2021-04-10           1752.0             16.0
43  25021  2021-04-17           1763.0             11.0
44  25021  2021-04-24           1768.0              5.0
45  25021  2021-05-01           1773.0              5.0
46  25021  2021-05-08           1778.0              5.0
47  25021  2021-05-15           1780.0              2.0
48  25021  2021-05-22           1783.0              3.0
49  25021  2021-05-29           1789.0              6.0
50  25021  2021-06-05           1792.0              3.0
51  25021  2021-06-12           1796.0              4.0
52  25021  2021-06-19           1798.0              2.0
53  25021  2021-06-26           1802.0              4.0
54  25021  2021-07-03           1804.0              2.0
55  25021  2021-07-10           1806.0              2.0
56  25021  2021-07-17           1807.0              1.0
57  25021  2021-07-24           1808.0              1.0
58  25021  2021-07-31           1810.0              2.0
59  25021  2021-08-07           1811.0              1.0
60  25021  2021-08-14           1814.0              3.0
61  25021  2021-08-21           1818.0              4.0
62  25021  2021-08-28           1821.0              3.0
63  25021  2021-09-04           1822.0              1.0
64  25021  2021-09-11           1824.0              2.0
65  25021  2021-09-18           1834.0             10.0
66  25021  2021-09-25           1838.0              4.0
67  25021  2021-10-02           1845.0              7.0
68  25021  2021-10-09           1849.0              4.0
69  25021  2021-10-16           1853.0              4.0
70  25021  2021-10-23           1855.0              2.0
71  25021  2021-10-30           1862.0              7.0
72  25021  2021-11-06           1865.0              3.0
73  25021  2021-11-13           1871.0              6.0
74  25021  2021-11-20           1879.0              8.0
75  25021  2021-11-27           1883.0              4.0
76  25021  2021-12-04           1892.0              9.0
77  25021  2021-12-11           1908.0             16.0
78  25021  2021-12-18           1923.0             15.0
79  25021  2021-12-25           1939.0             16.0
80  25021  2022-01-01           1954.0             15.0
81  25021  2022-01-08           1977.0             23.0
82  25021  2022-01-15           2004.0             27.0
83  25021  2022-01-22           2038.0             34.0
84  25021  2022-01-29           2079.0             41.0
85  25021  2022-02-05           2125.0             46.0
86  25021  2022-02-12           2163.0             38.0
87  25021  2022-02-19           2189.0             26.0
88  25021  2022-02-26           2216.0             27.0
89  25021  2022-03-05           2228.0             12.0
90  25021  2022-03-12           2242.0             14.0
91  25021  2022-03-19           1865.0           -377.0
92  25021  2022-03-26           1870.0              5.0
93  25021  2022-04-02           1875.0              5.0
94  25021  2022-04-09           1875.0              0.0
95  25021  2022-04-16           1880.0              5.0
96  25021  2022-04-23           1887.0              7.0
97  25021  2022-04-30           1890.0              3.0
98  25021  2022-05-07           1897.0              7.0

In [38]:
df[df.True_inc_deaths<0].True_inc_deaths.value_counts()

True_inc_deaths
-1.0      1849
-2.0       275
-3.0        73
-4.0        54
-5.0        35
-6.0        20
-9.0        15
-7.0        13
-8.0        11
-12.0        9
-10.0        9
-14.0        7
-11.0        5
-13.0        4
-16.0        3
-19.0        3
-17.0        3
-41.0        2
-24.0        2
-38.0        2
-20.0        2
-23.0        2
-34.0        2
-110.0       2
-48.0        1
-39.0        1
-489.0       1
-79.0        1
-124.0       1
-131.0       1
-46.0        1
-512.0       1
-54.0        1
-37.0        1
-45.0        1
-348.0       1
-339.0       1
-377.0       1
-792.0       1
-64.0        1
-312.0       1
-446.0       1
-362.0       1
-15.0        1
-18.0        1
-416.0       1
-21.0        1
-424.0       1
-29.0        1
Name: count, dtype: int64

In [42]:
df[df.True_inc_deaths<0].Date.value_counts()

Date
2021-03-06    102
2022-04-09     69
2021-06-19     65
2021-07-03     52
2021-03-20     52
2021-05-22     50
2021-06-12     49
2021-05-15     46
2021-05-01     45
2021-05-08     42
2021-06-05     41
2022-04-16     41
2021-03-13     41
2022-04-23     41
2020-08-08     40
2022-03-19     39
2021-07-10     38
2021-03-27     38
2021-05-29     38
2021-04-17     37
2020-12-12     37
2022-03-26     37
2021-11-27     36
2022-04-02     35
2022-04-30     34
2022-03-12     33
2021-07-17     32
2022-05-07     32
2021-07-24     31
2021-06-26     29
2021-04-03     28
2021-04-10     28
2020-10-03     27
2021-11-20     27
2021-07-31     26
2021-04-24     26
2020-11-21     26
2020-09-26     25
2020-08-01     24
2022-01-01     24
2020-10-17     23
2022-01-15     23
2020-12-05     22
2020-08-29     21
2021-12-11     21
2021-02-13     21
2021-12-18     20
2021-11-13     20
2020-12-19     19
2021-01-02     19
2021-10-16     19
2022-01-22     18
2020-08-22     18
2021-08-07     18
2021-10-02     18
2020-10-31     18
2020-07-25     17
2021-10-30     17
2022-02-19     17
2021-08-14     17
2022-02-26     17
2020-10-10     17
2021-11-06     16
2021-02-20     16
2022-03-05     16
2022-01-08     16
2020-10-24     16
2020-09-12     16
2022-02-05     15
2021-01-30     15
2020-06-27     15
2020-11-07     15
2020-07-18     15
2020-09-05     15
2020-11-28     15
2020-08-15     14
2020-12-26     14
2020-09-19     14
2021-09-04     13
2021-02-06     13
2020-11-14     13
2021-10-23     13
2021-02-27     12
2021-12-04     12
2021-01-09     11
2021-10-09     11
2020-07-11     11
2022-02-12     10
2021-09-18      9
2021-01-23      9
2020-07-04      9
2022-01-29      9
2021-12-25      9
2021-01-16      9
2021-08-21      9
2021-08-28      8
2021-09-25      7
2021-09-11      4
Name: count, dtype: int64