In [1]:
%%capture
%load_ext autoreload
%autoreload 2
from setup_nb_env import *

from epsampling.utils import load_csv
# pd.set_option('display.float_format', lambda x: '%.3f' % x)

DATA_DIR = '/work/users/k/4/k4thryn/Repos/EpSampling/data/'
DT = datetime.today().strftime('%Y%m%d-%H%M%S')

In [2]:
def drop_sers_with_nans(df, from_axis='rows'):
    
    if df.isnull().values.any()==True:
        print(f'Dropped {from_axis} with NaNs!')

        if from_axis=='rows':
            dff = df.dropna(axis=0, inplace=False)
            print(f'Num rows before: {df.shape[0]}')
            print(f'Num rows after: {dff.shape[0]}')
            
        elif from_axis=='cols':
            dff = df.dropna(axis=1, inplace=False)
            print(f'Num cols before: {(df.shape[1])}')
            print(f'Num cols after: {(dff.shape[1])}')
            
        return dff
    
    else:
        print(f'No NaNs! :)')
        return df

In [3]:
timestamp = '20240927-114300'

fpath = os.path.join(DATA_DIR,'processed',f'formatted_state_fips_{timestamp}.csv')
df_fips = pd.read_csv(fpath)

# fpath = os.path.join(DATA_DIR,'processed',f'formatted_COVIDhub-ensemble_{timestamp}.csv')
# df_hub = pd.read_csv(fpath)

# fpath = os.path.join(DATA_DIR,'processed',f'formatted_nytimes-us-counties_{timestamp}.csv')
# df_nyt = pd.read_csv(fpath)

fpath = os.path.join(DATA_DIR,'processed',f'formatted_acs_results_{timestamp}.csv')
df_acs = pd.read_csv(fpath)

display(df_fips.head())
display(df_acs)

        State Postal  Fips
0     Alabama     AL     1
1      Alaska     AK     2
2     Arizona     AZ     4
3    Arkansas     AR     5
4  California     CA     6

,Fips,POP_x2,POP_M,POP_F,POP_A0004,POP_A0509,POP_A1014,POP_A1517,POP_A1819,POP_A20,...,HU_x15,HU_UIS01D,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS0509,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
0,2013,3409,2014,1395,122,103,151,106,52,37,...,1113,835,3,57,72,41,35,0,0,70
1,2016,5251,2995,2256,162,215,148,110,154,55,...,1456,417,70,242,275,154,79,180,12,27
2,2020,292545,149648,142897,20218,20836,18642,11308,7022,3885,...,118055,56649,16185,6372,12729,6852,4719,6892,2642,5015
3,2050,18514,9724,8790,1902,1923,1696,1028,612,261,...,5992,4826,125,305,228,56,65,150,9,228
4,2060,849,480,369,67,41,28,23,8,3,...,922,711,33,23,29,51,12,7,0,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,42459,21850,20609,2657,3456,3008,1824,1193,485,...,19174,11446,847,478,1023,559,514,404,73,3830
3138,56039,23319,12280,11039,1068,1032,1475,575,569,64,...,13255,7788,1314,555,1098,1056,505,404,97,438
3139,56041,20514,10437,10077,1413,1712,1762,986,341,129,...,8819,5230,606,99,237,230,424,125,62,1806
3140,56043,7768,4004,3764,399,321,606,442,191,76,...,3842,2847,87,128,267,128,22,17,5,341
3141,56045,6891,3684,3207,308,542,227,315,225,94,...,3431,2376,63,97,55,75,55,35,9,666

In [4]:
## Remove duplicate columns
df = df_acs.drop_duplicates()
df

,Fips,POP_x2,POP_M,POP_F,POP_A0004,POP_A0509,POP_A1014,POP_A1517,POP_A1819,POP_A20,...,HU_x15,HU_UIS01D,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS0509,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
0,2013,3409,2014,1395,122,103,151,106,52,37,...,1113,835,3,57,72,41,35,0,0,70
1,2016,5251,2995,2256,162,215,148,110,154,55,...,1456,417,70,242,275,154,79,180,12,27
2,2020,292545,149648,142897,20218,20836,18642,11308,7022,3885,...,118055,56649,16185,6372,12729,6852,4719,6892,2642,5015
3,2050,18514,9724,8790,1902,1923,1696,1028,612,261,...,5992,4826,125,305,228,56,65,150,9,228
4,2060,849,480,369,67,41,28,23,8,3,...,922,711,33,23,29,51,12,7,0,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,42459,21850,20609,2657,3456,3008,1824,1193,485,...,19174,11446,847,478,1023,559,514,404,73,3830
3138,56039,23319,12280,11039,1068,1032,1475,575,569,64,...,13255,7788,1314,555,1098,1056,505,404,97,438
3139,56041,20514,10437,10077,1413,1712,1762,986,341,129,...,8819,5230,606,99,237,230,424,125,62,1806
3140,56043,7768,4004,3764,399,321,606,442,191,76,...,3842,2847,87,128,267,128,22,17,5,341
3141,56045,6891,3684,3207,308,542,227,315,225,94,...,3431,2376,63,97,55,75,55,35,9,666

## <font color=magenta> _NEXT ToDo:_ Continue working on dropping duplicate columns and then highly correlated columns ...

In [5]:
def drop_duplicate_cols(df):
    uniq, idxs = np.unique(df, return_index=True, axis=1)
    return pd.DataFrame(uniq, index=df.index, columns=df.columns[idxs])

dff = drop_duplicate_cols(df)
display(df, dff)

,Fips,POP_x2,POP_M,POP_F,POP_A0004,POP_A0509,POP_A1014,POP_A1517,POP_A1819,POP_A20,...,HU_x15,HU_UIS01D,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS0509,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
0,2013,3409,2014,1395,122,103,151,106,52,37,...,1113,835,3,57,72,41,35,0,0,70
1,2016,5251,2995,2256,162,215,148,110,154,55,...,1456,417,70,242,275,154,79,180,12,27
2,2020,292545,149648,142897,20218,20836,18642,11308,7022,3885,...,118055,56649,16185,6372,12729,6852,4719,6892,2642,5015
3,2050,18514,9724,8790,1902,1923,1696,1028,612,261,...,5992,4826,125,305,228,56,65,150,9,228
4,2060,849,480,369,67,41,28,23,8,3,...,922,711,33,23,29,51,12,7,0,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,42459,21850,20609,2657,3456,3008,1824,1193,485,...,19174,11446,847,478,1023,559,514,404,73,3830
3138,56039,23319,12280,11039,1068,1032,1475,575,569,64,...,13255,7788,1314,555,1098,1056,505,404,97,438
3139,56041,20514,10437,10077,1413,1712,1762,986,341,129,...,8819,5230,606,99,237,230,424,125,62,1806
3140,56043,7768,4004,3764,399,321,606,442,191,76,...,3842,2847,87,128,267,128,22,17,5,341
3141,56045,6891,3684,3207,308,542,227,315,225,94,...,3431,2376,63,97,55,75,55,35,9,666

,OCC_MBSA_ELCAM_L,IND_AFFHM_MQE,IND_PSMAW_M,HU_OCC_OPRgt200,HU_UIS50P,IND_WHT_x7,HU_UIS2049,EDU_PROF,HH_7pP,OCC_MBSA_CES_CM,...,POP_AIANNH,POP_AIAN,EDU_HS,POP_A3564,Fips,POP_M,POP_16p_EMP_x7,POP_A25p,POP_NH,POP_x2
0,0,0,0,0,0,0,0,1,1,2,...,1501,1505,1648,1760,2013,2014,2213,2598,3050,3409
1,0,6,9,11,12,47,180,14,21,17,...,523,549,2626,2471,2016,2995,3655,3838,4740,5251
2,1842,2985,428,499,2642,2860,6892,5415,2311,3709,...,19827,21150,94213,107273,2020,149648,144598,193312,264762,292545
3,32,90,250,239,9,19,150,102,543,31,...,15427,15640,6485,5770,2050,9724,6454,10025,18131,18514
4,0,0,0,0,0,2,7,1,12,3,...,266,282,411,384,2060,480,443,643,740,849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,165,3135,0,30,73,561,404,436,164,302,...,454,506,16349,16838,56037,21850,20884,27816,35626,42459
3138,209,67,0,74,97,175,404,496,0,179,...,30,30,6148,9875,56039,12280,14952,17659,19835,23319
3139,0,748,0,8,62,116,125,101,98,30,...,20,52,8432,7709,56041,10437,9688,13233,18533,20514
3140,63,106,0,0,5,70,17,75,94,41,...,38,71,2992,2958,56043,4004,3907,5423,6651,7768
3141,12,572,0,0,9,30,35,41,67,29,...,88,90,2980,2724,56045,3684,3044,4892,6763,6891