In [20]:
%%capture
%load_ext autoreload
%autoreload 2
from setup_nb_env import *

from epsampling.utils import load_csv
pd.set_option('display.float_format', lambda x: '%.2f' % x)
from epsampling.utils import drop_sers_with_nans
from epsampling.utils import date_str_to_int

DATA_DIR = '/work/users/k/4/k4thryn/Repos/EpSampling/data/'
DT = datetime.today().strftime('%Y%m%d-%H%M%S')

In [2]:
### LOAD CSV
timestamp = '20241002-004543'
fpath = os.path.join(DATA_DIR,'processed', f'processed_naive_deaths_{timestamp}.csv')
df_deaths = pd.read_csv(fpath)

### CLEAN
## Drop rows with nans.
df_deaths.dropna(inplace=True)
## Drop samples with negative inc deaths.
df_deaths = df_deaths[df_deaths.True_inc_deaths >= 0]
# display(df_deaths)

In [5]:
from epsampling.utils import drop_duplicate_cols

timestamp = '20241001-223952'
fpath = os.path.join(DATA_DIR,'processed',f'formatted_acs_results_{timestamp}.csv')
df_acs = pd.read_csv(fpath,index_col='Fips')
print(df_acs.shape)
## Remove duplicate columns.
df_acs = drop_duplicate_cols(df_acs)
# display(df_acs.head())

(3142, 190)

In [7]:
df = df_deaths.merge(df_acs, on='Fips')
df.reset_index(inplace=True, drop=True)
display(df)

,Fips,State_fips,Pop,State_pop,Ratio,Date,Proj_inc_deaths,True_cum_deaths,Cum_deaths_tm1,True_inc_deaths,...,POP_F,POP_AIANNH,POP_AIAN,EDU_HS,POP_A3564,POP_M,POP_16p_EMP_x7,POP_A25p,POP_NH,POP_x2
0,1001,1,58239,4997675,0.011653,20200620,83.302156,9.0,6.0,3.0,...,30033,98,98,20751,22690,28206,25871,39614,56464,58239
1,1001,1,58239,4997675,0.011653,20200627,68.179357,12.0,9.0,3.0,...,30033,98,98,20751,22690,28206,25871,39614,56464,58239
2,1001,1,58239,4997675,0.011653,20200704,76.238975,13.0,12.0,1.0,...,30033,98,98,20751,22690,28206,25871,39614,56464,58239
3,1001,1,58239,4997675,0.011653,20200711,88.362530,15.0,13.0,2.0,...,30033,98,98,20751,22690,28206,25871,39614,56464,58239
4,1001,1,58239,4997675,0.011653,20200718,114.279381,21.0,15.0,6.0,...,30033,98,98,20751,22690,28206,25871,39614,56464,58239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306758,56045,56,6891,576641,0.011950,20220409,8.000000,18.0,18.0,0.0,...,3207,88,90,2980,2724,3684,3044,4892,6763,6891
306759,56045,56,6891,576641,0.011950,20220416,5.000000,18.0,18.0,0.0,...,3207,88,90,2980,2724,3684,3044,4892,6763,6891
306760,56045,56,6891,576641,0.011950,20220423,4.000000,18.0,18.0,0.0,...,3207,88,90,2980,2724,3684,3044,4892,6763,6891
306761,56045,56,6891,576641,0.011950,20220430,4.000000,18.0,18.0,0.0,...,3207,88,90,2980,2724,3684,3044,4892,6763,6891
306762,56045,56,6891,576641,0.011950,20220507,4.000000,18.0,18.0,0.0,...,3207,88,90,2980,2724,3684,3044,4892,6763,6891

In [8]:
df.columns[:20]

Index(['Fips', 'State_fips', 'Pop', 'State_pop', 'Ratio', 'Date',
       'Proj_inc_deaths', 'True_cum_deaths', 'Cum_deaths_tm1',
       'True_inc_deaths', 'Naive_inc_deaths', 'OCC_MBSA_ELCAM_L',
       'IND_AFFHM_MQE', 'IND_PSMAW_M', 'HU_OCC_OPRgt200', 'HU_UIS50P',
       'IND_WHT_x7', 'HU_UIS2049', 'EDU_PROF', 'HH_7pP'],
      dtype='object')

In [10]:
### LOAD CSV
timestamp = '20240928-145111'
fpath = os.path.join(DATA_DIR,'processed', f'formatted_state_fips_{timestamp}.csv')
df_fips = pd.read_csv(fpath)
# df_fips

In [11]:
df_fips

                   State Postal  Fips
0                Alabama     AL     1
1                 Alaska     AK     2
2                Arizona     AZ     4
3               Arkansas     AR     5
4             California     CA     6
5               Colorado     CO     8
6            Connecticut     CT     9
7               Delaware     DE    10
8   District of Columbia     DC    11
9                Florida     FL    12
10               Georgia     GA    13
11                Hawaii     HI    15
12                 Idaho     ID    16
13              Illinois     IL    17
14               Indiana     IN    18
15                  Iowa     IA    19
16                Kansas     KS    20
17              Kentucky     KY    21
18             Louisiana     LA    22
19                 Maine     ME    23
20              Maryland     MD    24
21         Massachusetts     MA    25
22              Michigan     MI    26
23             Minnesota     MN    27
24           Mississippi     MS    28
25              Missouri     MO    29
26               Montana     MT    30
27              Nebraska     NE    31
28                Nevada     NV    32
29         New Hampshire     NH    33
30            New Jersey     NJ    34
31            New Mexico     NM    35
32              New York     NY    36
33        North Carolina     NC    37
34          North Dakota     ND    38
35                  Ohio     OH    39
36              Oklahoma     OK    40
37                Oregon     OR    41
38          Pennsylvania     PA    42
39           Puerto Rico     PR    72
40          Rhode Island     RI    44
41        South Carolina     SC    45
42          South Dakota     SD    46
43             Tennessee     TN    47
44                 Texas     TX    48
45                  Utah     UT    49
46               Vermont     VT    50
47              Virginia     VA    51
48        Virgin Islands     VI    78
49            Washington     WA    53
50         West Virginia     WV    54
51             Wisconsin     WI    55
52               Wyoming     WY    56

In [16]:

fips_dict = {}
for r in df_fips.itertuples():
    fips_dict[r.Fips] = r.Postal
# fips_dict

In [17]:
df['State'] = df.apply(lambda x: fips_dict[x.State_fips], axis=1)
df

,Fips,State_fips,Pop,State_pop,Ratio,Date,Proj_inc_deaths,True_cum_deaths,Cum_deaths_tm1,True_inc_deaths,...,POP_AIANNH,POP_AIAN,EDU_HS,POP_A3564,POP_M,POP_16p_EMP_x7,POP_A25p,POP_NH,POP_x2,State
0,1001,1,58239,4997675,0.011653,20200620,83.302156,9.0,6.0,3.0,...,98,98,20751,22690,28206,25871,39614,56464,58239,AL
1,1001,1,58239,4997675,0.011653,20200627,68.179357,12.0,9.0,3.0,...,98,98,20751,22690,28206,25871,39614,56464,58239,AL
2,1001,1,58239,4997675,0.011653,20200704,76.238975,13.0,12.0,1.0,...,98,98,20751,22690,28206,25871,39614,56464,58239,AL
3,1001,1,58239,4997675,0.011653,20200711,88.362530,15.0,13.0,2.0,...,98,98,20751,22690,28206,25871,39614,56464,58239,AL
4,1001,1,58239,4997675,0.011653,20200718,114.279381,21.0,15.0,6.0,...,98,98,20751,22690,28206,25871,39614,56464,58239,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306758,56045,56,6891,576641,0.011950,20220409,8.000000,18.0,18.0,0.0,...,88,90,2980,2724,3684,3044,4892,6763,6891,WY
306759,56045,56,6891,576641,0.011950,20220416,5.000000,18.0,18.0,0.0,...,88,90,2980,2724,3684,3044,4892,6763,6891,WY
306760,56045,56,6891,576641,0.011950,20220423,4.000000,18.0,18.0,0.0,...,88,90,2980,2724,3684,3044,4892,6763,6891,WY
306761,56045,56,6891,576641,0.011950,20220430,4.000000,18.0,18.0,0.0,...,88,90,2980,2724,3684,3044,4892,6763,6891,WY
306762,56045,56,6891,576641,0.011950,20220507,4.000000,18.0,18.0,0.0,...,88,90,2980,2724,3684,3044,4892,6763,6891,WY

In [30]:

# EDU_DOCT doctoral degree population
# OCC_SALES sales occupations
# POP_F female pop
# HU_VAC vacant housing units

dff = df[['True_inc_deaths', 'Fips', 'State', 'Date',  
          'Proj_inc_deaths', 'Naive_inc_deaths', 'Cum_deaths_tm1',
          'Pop', 'Ratio','True_cum_deaths', 
          'EDU_DOCT', 'OCC_SALES', 'POP_F', 'HU_VAC'
        ]]

dff

,True_inc_deaths,Fips,State,Date,Proj_inc_deaths,Naive_inc_deaths,Cum_deaths_tm1,Pop,Ratio,True_cum_deaths,EDU_DOCT,OCC_SALES,POP_F,HU_VAC
0,3.00,1001,AL,20200620,83.30,0.97,6.00,58239,0.01,9.00,464,5656,30033,2314
1,3.00,1001,AL,20200627,68.18,0.79,9.00,58239,0.01,12.00,464,5656,30033,2314
2,1.00,1001,AL,20200704,76.24,0.89,12.00,58239,0.01,13.00,464,5656,30033,2314
3,2.00,1001,AL,20200711,88.36,1.03,13.00,58239,0.01,15.00,464,5656,30033,2314
4,6.00,1001,AL,20200718,114.28,1.33,15.00,58239,0.01,21.00,464,5656,30033,2314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306758,0.00,56045,WY,20220409,8.00,0.10,18.00,6891,0.01,18.00,43,373,3207,677
306759,0.00,56045,WY,20220416,5.00,0.06,18.00,6891,0.01,18.00,43,373,3207,677
306760,0.00,56045,WY,20220423,4.00,0.05,18.00,6891,0.01,18.00,43,373,3207,677
306761,0.00,56045,WY,20220430,4.00,0.05,18.00,6891,0.01,18.00,43,373,3207,677
306762,0.00,56045,WY,20220507,4.00,0.05,18.00,6891,0.01,18.00,43,373,3207,677

In [37]:
dfff = dff.sort_values(['Fips','Date'])
dfff

,True_inc_deaths,Fips,State,Date,Proj_inc_deaths,Naive_inc_deaths,Cum_deaths_tm1,Pop,Ratio,True_cum_deaths,EDU_DOCT,OCC_SALES,POP_F,HU_VAC
0,3.00,1001,AL,20200620,83.30,0.97,6.00,58239,0.01,9.00,464,5656,30033,2314
1,3.00,1001,AL,20200627,68.18,0.79,9.00,58239,0.01,12.00,464,5656,30033,2314
2,1.00,1001,AL,20200704,76.24,0.89,12.00,58239,0.01,13.00,464,5656,30033,2314
3,2.00,1001,AL,20200711,88.36,1.03,13.00,58239,0.01,15.00,464,5656,30033,2314
4,6.00,1001,AL,20200718,114.28,1.33,15.00,58239,0.01,21.00,464,5656,30033,2314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306758,0.00,56045,WY,20220409,8.00,0.10,18.00,6891,0.01,18.00,43,373,3207,677
306759,0.00,56045,WY,20220416,5.00,0.06,18.00,6891,0.01,18.00,43,373,3207,677
306760,0.00,56045,WY,20220423,4.00,0.05,18.00,6891,0.01,18.00,43,373,3207,677
306761,0.00,56045,WY,20220430,4.00,0.05,18.00,6891,0.01,18.00,43,373,3207,677
306762,0.00,56045,WY,20220507,4.00,0.05,18.00,6891,0.01,18.00,43,373,3207,677

In [46]:
# dfff[dfff.Fips==37183]

,True_inc_deaths,Fips,State,Date,Proj_inc_deaths,Naive_inc_deaths,Cum_deaths_tm1,Pop,Ratio,True_cum_deaths,EDU_DOCT,OCC_SALES,POP_F,HU_VAC
192964,3.00,37183,NC,20200620,122.95,13.20,41.00,1112883,0.11,44.00,19892,117559,568699,32528
192965,2.00,37183,NC,20200627,100.31,10.77,44.00,1112883,0.11,46.00,19892,117559,568699,32528
192966,3.00,37183,NC,20200704,119.40,12.82,46.00,1112883,0.11,49.00,19892,117559,568699,32528
192967,17.00,37183,NC,20200711,100.12,10.75,49.00,1112883,0.11,66.00,19892,117559,568699,32528
192968,23.00,37183,NC,20200718,120.18,12.90,66.00,1112883,0.11,89.00,19892,117559,568699,32528
192969,16.00,37183,NC,20200725,131.00,14.06,89.00,1112883,0.11,105.00,19892,117559,568699,32528
192970,27.00,37183,NC,20200801,152.00,16.32,105.00,1112883,0.11,132.00,19892,117559,568699,32528
192971,36.00,37183,NC,20200808,162.00,17.39,132.00,1112883,0.11,168.00,19892,117559,568699,32528
192972,14.00,37183,NC,20200815,208.00,22.33,168.00,1112883,0.11,182.00,19892,117559,568699,32528
192973,6.00,37183,NC,20200822,149.00,15.99,182.00,1112883,0.11,188.00,19892,117559,568699,32528
192974,11.00,37183,NC,20200829,165.00,17.71,188.00,1112883,0.11,199.00,19892,117559,568699,32528
192975,11.00,37183,NC,20200905,157.00,16.85,199.00,1112883,0.11,210.00,19892,117559,568699,32528
192976,3.00,37183,NC,20200912,176.00,18.89,210.00,1112883,0.11,213.00,19892,117559,568699,32528
192977,15.00,37183,NC,20200919,157.00,16.85,213.00,1112883,0.11,228.00,19892,117559,568699,32528
192978,15.00,37183,NC,20200926,171.00,18.36,228.00,1112883,0.11,243.00,19892,117559,568699,32528
192979,16.00,37183,NC,20201003,171.00,18.36,243.00,1112883,0.11,259.00,19892,117559,568699,32528
192980,1.00,37183,NC,20201010,177.00,19.00,259.00,1112883,0.11,260.00,19892,117559,568699,32528
192981,1.00,37183,NC,20201017,162.00,17.39,260.00,1112883,0.11,261.00,19892,117559,568699,32528
192982,9.00,37183,NC,20201024,162.00,17.39,261.00,1112883,0.11,270.00,19892,117559,568699,32528
192983,5.00,37183,NC,20201031,198.00,21.25,270.00,1112883,0.11,275.00,19892,117559,568699,32528
192984,5.00,37183,NC,20201107,221.00,23.72,275.00,1112883,0.11,280.00,19892,117559,568699,32528
192985,0.00,37183,NC,20201114,223.00,23.94,280.00,1112883,0.11,280.00,19892,117559,568699,32528
192986,5.00,37183,NC,20201121,200.00,21.47,280.00,1112883,0.11,285.00,19892,117559,568699,32528
192987,4.00,37183,NC,20201128,257.00,27.59,285.00,1112883,0.11,289.00,19892,117559,568699,32528
192988,15.00,37183,NC,20201205,242.00,25.98,289.00,1112883,0.11,304.00,19892,117559,568699,32528
192989,18.00,37183,NC,20201212,315.00,33.81,304.00,1112883,0.11,322.00,19892,117559,568699,32528
192990,14.00,37183,NC,20201219,347.00,37.25,322.00,1112883,0.11,336.00,19892,117559,568699,32528
192991,1.00,37183,NC,20201226,408.00,43.80,336.00,1112883,0.11,337.00,19892,117559,568699,32528
192992,11.00,37183,NC,20210102,367.00,39.40,337.00,1112883,0.11,348.00,19892,117559,568699,32528
192993,14.00,37183,NC,20210109,366.00,39.29,348.00,1112883,0.11,362.00,19892,117559,568699,32528
192994,32.00,37183,NC,20210116,537.00,57.65,362.00,1112883,0.11,394.00,19892,117559,568699,32528
192995,19.00,37183,NC,20210123,596.00,63.98,394.00,1112883,0.11,413.00,19892,117559,568699,32528
192996,15.00,37183,NC,20210130,583.00,62.58,413.00,1112883,0.11,428.00,19892,117559,568699,32528
192997,68.00,37183,NC,20210206,622.00,66.77,428.00,1112883,0.11,496.00,19892,117559,568699,32528
192998,9.00,37183,NC,20210213,613.00,65.80,496.00,1112883,0.11,505.00,19892,117559,568699,32528
192999,18.00,37183,NC,20210220,515.00,55.28,505.00,1112883,0.11,523.00,19892,117559,568699,32528
193000,29.00,37183,NC,20210306,314.00,33.71,521.00,1112883,0.11,550.00,19892,117559,568699,32528
193001,22.00,37183,NC,20210313,253.00,27.16,550.00,1112883,0.11,572.00,19892,117559,568699,32528
193002,14.00,37183,NC,20210320,194.00,20.83,572.00,1112883,0.11,586.00,19892,117559,568699,32528
193003,92.00,37183,NC,20210327,132.00,14.17,586.00,1112883,0.11,678.00,19892,117559,568699,32528
193004,6.00,37183,NC,20210403,140.00,15.03,678.00,1112883,0.11,684.00,19892,117559,568699,32528
193005,9.00,37183,NC,20210410,132.00,14.17,684.00,1112883,0.11,693.00,19892,117559,568699,32528
193006,19.00,37183,NC,20210417,111.00,11.92,693.00,1112883,0.11,712.00,19892,117559,568699,32528
193007,12.00,37183,NC,20210424,130.00,13.96,712.00,1112883,0.11,724.00,19892,117559,568699,32528
193008,6.00,37183,NC,20210501,132.00,14.17,724.00,1112883,0.11,730.00,19892,117559,568699,32528
193009,3.00,37183,NC,20210515,115.00,12.35,729.00,1112883,0.11,732.00,19892,117559,568699,32528
193010,0.00,37183,NC,20210522,85.00,9.12,732.00,1112883,0.11,732.00,19892,117559,568699,32528
193011,3.00,37183,NC,20210529,77.00,8.27,732.00,1112883,0.11,735.00,19892,117559,568699,32528
193012,2.00,37183,NC,20210605,85.00,9.12,735.00,1112883,0.11,737.00,19892,117559,568699,32528
193013,0.00,37183,NC,20210612,69.00,7.41,737.00,1112883,0.11,737.00,19892,117559,568699,32528
193014,1.00,37183,NC,20210619,80.00,8.59,737.00,1112883,0.11,738.00,19892,117559,568699,32528
193015,4.00,37183,NC,20210626,67.00,7.19,738.00,1112883,0.11,742.00,19892,117559,568699,32528
193016,3.00,37183,NC,20210710,37.00,3.97,737.00,1112883,0.11,740.00,19892,117559,568699,32528
193017,0.00,37183,NC,20210717,40.00,4.29,740.00,1112883,0.11,740.00,19892,117559,568699,32528
193018,9.00,37183,NC,20210724,45.00,4.83,740.00,1112883,0.11,749.00,19892,117559,568699,32528
193019,1.00,37183,NC,20210731,54.00,5.80,749.00,1112883,0.11,750.00,19892,117559,568699,32528
193020,8.00,37183,NC,20210807,78.00,8.37,750.00,1112883,0.11,758.00,19892,117559,568699,32528
193021,1.00,37183,NC,20210814,120.00,12.88,758.00,1112883,0.11,759.00,19892,117559,568699,32528
193022,4.00,37183,NC,20210821,118.00,12.67,759.00,1112883,0.11,763.00,19892,117559,568699,32528
193023,13.00,37183,NC,20210828,217.00,23.29,763.00,1112883,0.11,776.00,19892,117559,568699,32528
193024,6.00,37183,NC,20210904,324.00,34.78,776.00,1112883,0.11,782.00,19892,117559,568699,32528
193025,26.00,37183,NC,20210911,416.00,44.66,782.00,1112883,0.11,808.00,19892,117559,568699,32528
193026,14.00,37183,NC,20210918,397.00,42.62,808.00,1112883,0.11,822.00,19892,117559,568699,32528
193027,17.00,37183,NC,20210925,521.00,55.93,822.00,1112883,0.11,839.00,19892,117559,568699,32528
193028,13.00,37183,NC,20211002,486.00,52.17,839.00,1112883,0.11,852.00,19892,117559,568699,32528
193029,17.00,37183,NC,20211009,471.00,50.56,852.00,1112883,0.11,869.00,19892,117559,568699,32528
193030,12.00,37183,NC,20211016,451.00,48.41,869.00,1112883,0.11,881.00,19892,117559,568699,32528
193031,7.00,37183,NC,20211023,336.00,36.07,881.00,1112883,0.11,888.00,19892,117559,568699,32528
193032,8.00,37183,NC,20211030,272.00,29.20,888.00,1112883,0.11,896.00,19892,117559,568699,32528
193033,0.00,37183,NC,20211106,228.00,24.48,896.00,1112883,0.11,896.00,19892,117559,568699,32528
193034,12.00,37183,NC,20211113,186.00,19.97,896.00,1112883,0.11,908.00,19892,117559,568699,32528
193035,2.00,37183,NC,20211120,149.00,15.99,908.00,1112883,0.11,910.00,19892,117559,568699,32528
193036,5.00,37183,NC,20211127,147.00,15.78,910.00,1112883,0.11,915.00,19892,117559,568699,32528
193037,1.00,37183,NC,20211211,123.00,13.20,910.00,1112883,0.11,911.00,19892,117559,568699,32528
193038,2.00,37183,NC,20211218,146.00,15.67,911.00,1112883,0.11,913.00,19892,117559,568699,32528
193039,3.00,37183,NC,20211225,164.00,17.61,913.00,1112883,0.11,916.00,19892,117559,568699,32528
193040,4.00,37183,NC,20220101,144.00,15.46,916.00,1112883,0.11,920.00,19892,117559,568699,32528
193041,0.00,37183,NC,20220108,184.00,19.75,920.00,1112883,0.11,920.00,19892,117559,568699,32528
193042,19.00,37183,NC,20220115,261.00,28.02,920.00,1112883,0.11,939.00,19892,117559,568699,32528
193043,7.00,37183,NC,20220122,372.00,39.93,939.00,1112883,0.11,946.00,19892,117559,568699,32528
193044,21.00,37183,NC,20220129,345.00,37.04,946.00,1112883,0.11,967.00,19892,117559,568699,32528
193045,2.00,37183,NC,20220205,430.00,46.16,967.00,1112883,0.11,969.00,19892,117559,568699,32528
193046,12.00,37183,NC,20220212,453.00,48.63,969.00,1112883,0.11,981.00,19892,117559,568699,32528
193047,28.00,37183,NC,20220219,561.00,60.22,981.00,1112883,0.11,1009.00,19892,117559,568699,32528
193048,10.00,37183,NC,20220226,476.00,51.10,1009.00,1112883,0.11,1019.00,19892,117559,568699,32528
193049,11.00,37183,NC,20220305,332.00,35.64,1019.00,1112883,0.11,1030.00,19892,117559,568699,32528
193050,6.00,37183,NC,20220312,233.00,25.01,1030.00,1112883,0.11,1036.00,19892,117559,568699,32528
193051,2.00,37183,NC,20220319,150.00,16.10,1036.00,1112883,0.11,1038.00,19892,117559,568699,32528
193052,7.00,37183,NC,20220326,127.00,13.63,1038.00,1112883,0.11,1045.00,19892,117559,568699,32528
193053,1.00,37183,NC,20220402,115.00,12.35,1045.00,1112883,0.11,1046.00,19892,117559,568699,32528
193054,2.00,37183,NC,20220409,55.00,5.90,1046.00,1112883,0.11,1048.00,19892,117559,568699,32528
193055,2.00,37183,NC,20220416,41.00,4.40,1048.00,1112883,0.11,1050.00,19892,117559,568699,32528
193056,2.00,37183,NC,20220423,60.00,6.44,1050.00,1112883,0.11,1052.00,19892,117559,568699,32528
193057,4.00,37183,NC,20220430,33.00,3.54,1052.00,1112883,0.11,1056.00,19892,117559,568699,32528
193058,61.00,37183,NC,20220507,33.00,3.54,1056.00,1112883,0.11,1117.00,19892,117559,568699,32528

In [48]:
dffff = pd.concat([dfff[:3], dfff[19912:19915], dfff[192964:192967]])
dffff

,True_inc_deaths,Fips,State,Date,Proj_inc_deaths,Naive_inc_deaths,Cum_deaths_tm1,Pop,Ratio,True_cum_deaths,EDU_DOCT,OCC_SALES,POP_F,HU_VAC
0,3.00,1001,AL,20200620,83.30,0.97,6.00,58239,0.01,9.00,464,5656,30033,2314
1,3.00,1001,AL,20200627,68.18,0.79,9.00,58239,0.01,12.00,464,5656,30033,2314
2,1.00,1001,AL,20200704,76.24,0.89,12.00,58239,0.01,13.00,464,5656,30033,2314
19912,1.00,6047,CA,20200620,473.83,3.35,7.00,279150,0.01,8.00,827,19019,137444,5149
19913,3.00,6047,CA,20200627,427.02,3.02,8.00,279150,0.01,11.00,827,19019,137444,5149
19914,0.00,6047,CA,20200704,451.50,3.19,11.00,279150,0.01,11.00,827,19019,137444,5149
192964,3.00,37183,NC,20200620,122.95,13.20,41.00,1112883,0.11,44.00,19892,117559,568699,32528
192965,2.00,37183,NC,20200627,100.31,10.77,44.00,1112883,0.11,46.00,19892,117559,568699,32528
192966,3.00,37183,NC,20200704,119.40,12.82,46.00,1112883,0.11,49.00,19892,117559,568699,32528

In [50]:
dffff.columns

Index(['True_inc_deaths', 'Fips', 'State', 'Date', 'Proj_inc_deaths',
       'Naive_inc_deaths', 'Cum_deaths_tm1', 'Pop', 'Ratio', 'True_cum_deaths',
       'EDU_DOCT', 'OCC_SALES', 'POP_F', 'HU_VAC'],
      dtype='object')

In [79]:
df = dffff.rename({'True_inc_deaths':'True inc',  
                   'Proj_inc_deaths' :'State pred inc',
                   'Naive_inc_deaths': 'Naive inc',
                   'True_cum_deaths':'True cum',
                   'Pop':'Total pop', 'Ratio':'Pop ratio',
                   'EDU_DOCT':'Edu Doct', 
                   'OCC_SALES':'Occ Sales', 
                   'POP_F':'Pop F', 
                   'HU_VAC':'HU Vac'
#                    ,
#                    ,
#                    ,
                  }
                  , axis=1)

cdict = {1001: 'Autauga', 6047:'Merced',37183: 'Wake'}
df['County'] = df.apply(lambda x: cdict[x.Fips], axis=1)

df = df[['County','State','Date', 'True inc','State pred inc',
         'Naive inc',
         'True cum','Total pop','Pop ratio',
        'Edu Doct', 'Occ Sales', 'Pop F', 'HU Vac']]
# df

df

,County,State,Date,True inc,State pred inc,Naive inc,True cum,Total pop,Pop ratio,Edu Doct,Occ Sales,Pop F,HU Vac
0,Autauga,AL,20200620,3.00,83.30,0.97,9.00,58239,0.01,464,5656,30033,2314
1,Autauga,AL,20200627,3.00,68.18,0.79,12.00,58239,0.01,464,5656,30033,2314
2,Autauga,AL,20200704,1.00,76.24,0.89,13.00,58239,0.01,464,5656,30033,2314
19912,Merced,CA,20200620,1.00,473.83,3.35,8.00,279150,0.01,827,19019,137444,5149
19913,Merced,CA,20200627,3.00,427.02,3.02,11.00,279150,0.01,827,19019,137444,5149
19914,Merced,CA,20200704,0.00,451.50,3.19,11.00,279150,0.01,827,19019,137444,5149
192964,Wake,NC,20200620,3.00,122.95,13.20,44.00,1112883,0.11,19892,117559,568699,32528
192965,Wake,NC,20200627,2.00,100.31,10.77,46.00,1112883,0.11,19892,117559,568699,32528
192966,Wake,NC,20200704,3.00,119.40,12.82,49.00,1112883,0.11,19892,117559,568699,32528

In [32]:
dfff = dff.sample(10)
dfff

,True_inc_deaths,Fips,State,Date,Proj_inc_deaths,Naive_inc_deaths,Cum_deaths_tm1,Pop,Ratio,True_cum_deaths,EDU_DOCT,OCC_SALES,POP_F,HU_VAC
206030,1.00,39143,OH,20200704,150.83,0.76,13.00,59013,0.01,14.00,83,4993,29497,2663
177571,5.00,35045,NM,20210612,17.00,0.99,487.00,122912,0.06,492.00,483,10567,61867,7433
196745,0.00,38059,ND,20210703,3.00,0.13,101.00,32916,0.04,101.00,94,3416,16347,1782
292476,1.00,54009,WV,20210227,48.00,0.60,49.00,22603,0.01,50.00,117,2220,11387,929
215049,0.00,40149,OK,20211113,148.00,0.41,31.00,11014,0.00,31.00,17,955,5533,1094
250903,0.00,48095,TX,20220402,316.00,0.03,11.00,3181,0.00,11.00,0,165,1254,640
174725,7.00,34033,NJ,20210213,478.00,3.35,150.00,64752,0.01,157.00,370,6613,32786,2974
91424,0.00,20105,KS,20200822,26.00,0.03,0.00,2952,0.00,0.00,10,300,1437,484
62755,0.00,17107,IL,20211106,172.00,0.38,89.00,28238,0.00,89.00,105,2541,14319,978
38128,1.00,13019,GA,20220319,348.00,0.60,80.00,18195,0.00,81.00,80,1334,9206,1448

In [27]:
# df.columns[15:30]

In [31]:

# EDU_DOCT doctoral degree population
# OCC_SALES sales occupations
# POP_F female pop
# HU_OCC occupied housing units

# display([x for x in df.columns])