In [27]:
%%capture
%load_ext autoreload
%autoreload 2
from setup_nb_env import *

# pd.set_option('display.float_format', lambda x: '%.3f' % x)

DATA_DIR = '/work/users/k/4/k4thryn/Repos/EpSampling/data/'
DT = datetime.today().strftime('%Y%m%d-%H%M%S')

# pd.set_option('display.max_rows', 8)

In [99]:
from epsampling.data_processing import get_hub_df, get_death_df, get_acs_df, \
get_full_target_df, get_only_acs_covs_df

_df_acs = get_acs_df(37)
df_hub = get_hub_df(state_fips=37)
df_death = get_death_df(state_fips=37)

100%|██████████| 210/210 [00:10<00:00, 20.02it/s]
100%|██████████| 100/100 [00:00<00:00, 694.21it/s]

In [100]:
df = get_full_target_df(df_hub, df_death, _df_acs)
df_acs = get_only_acs_covs_df(_df_acs)

with pd.option_context('display.max_rows', 8):
    display('Census features:', df_acs)
    display('COV19 Hub state-level predictions:',df_hub)
    display('NYT reported county-level deaths',df_death)

'Census features:'

,Fips,POP,POP_M,POP_F,POP_A0004,POP_A0509,POP_A1014,POP_A1517,POP_A1819,POP_A20,...,HU_x15,HU_UIS01D,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS0509,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
0,37001,169185,0.476916,0.523084,0.057529,0.061714,0.064805,0.039111,0.039572,0.016627,...,72651,0.665153,0.035030,0.023427,0.035870,0.049194,0.034728,0.029084,0.011507,0.116007
1,37003,36491,0.508838,0.491162,0.043846,0.046340,0.073306,0.039023,0.019073,0.010331,...,15997,0.693505,0.007189,0.015190,0.010127,0.004313,0.006876,0.000750,0.000000,0.262049
2,37005,10910,0.492392,0.507608,0.041613,0.054537,0.043355,0.031347,0.018057,0.008066,...,7721,0.789276,0.005699,0.012952,0.002331,0.020982,0.009584,0.001813,0.000000,0.157363
3,37007,22388,0.504690,0.495310,0.050116,0.051501,0.068608,0.036180,0.024031,0.010050,...,10027,0.709085,0.007380,0.010771,0.011668,0.024135,0.004189,0.007779,0.003391,0.221602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,37193,66335,0.499148,0.500852,0.049416,0.053185,0.061461,0.040084,0.021135,0.015135,...,31783,0.691565,0.000724,0.014977,0.015386,0.015323,0.007866,0.008495,0.012522,0.233144
97,37195,78844,0.475394,0.524606,0.059345,0.059941,0.070785,0.041550,0.027852,0.013711,...,36195,0.640586,0.028236,0.071833,0.042299,0.050090,0.009117,0.008261,0.009421,0.140157
98,37197,37198,0.500995,0.499005,0.049384,0.051105,0.070676,0.038792,0.017770,0.010915,...,17013,0.696938,0.003703,0.026098,0.007759,0.008640,0.005878,0.016517,0.001469,0.232998
99,37199,18357,0.494580,0.505420,0.045868,0.051043,0.053059,0.035136,0.017105,0.008934,...,11224,0.723717,0.005167,0.014077,0.032520,0.015324,0.006771,0.008909,0.000535,0.192979

'COV19 Hub state-level predictions:'

     State_fips      Date  Proj_state_inc_deaths
0            37  20200613             124.240120
1            37  20200620             122.952377
2            37  20200627             100.308655
3            37  20200704             119.399124
..          ...       ...                    ...
140          37  20230218              83.000000
141          37  20230225              69.000000
142          37  20230304              55.000000
143          37  20230311              44.000000

[144 rows x 3 columns]

'NYT reported county-level deaths'

       Fips      Date  True_county_cum_deaths  True_county_inc_deaths
0     37001  20200613                    32.0                     NaN
1     37001  20200620                    35.0                     3.0
2     37001  20200627                    36.0                     1.0
3     37001  20200704                    37.0                     1.0
...     ...       ...                     ...                     ...
9996  37199  20220416                    51.0                     0.0
9997  37199  20220423                    51.0                     0.0
9998  37199  20220430                    51.0                     0.0
9999  37199  20220507                    57.0                     6.0

[10000 rows x 4 columns]

In [70]:
display('Target-related attributes',df)

'Target-related attributes'

,Date,State_fips,Fips,Pop,State_pop,Ratio,Proj_state_inc_deaths,True_state_inc_deaths,True_county_cum_deaths,True_county_inc_deaths,Naive_proj_deaths,Naive_true_deaths
0,20200620,37,37001,169185,10367022,0.016320,122.952377,104.0,35.0,3.0,2.006526,1.697232
1,20200627,37,37001,169185,10367022,0.016320,100.308655,95.0,36.0,1.0,1.636991,1.550356
2,20200704,37,37001,169185,10367022,0.016320,119.399124,80.0,37.0,1.0,1.948538,1.305563
3,20200711,37,37001,169185,10367022,0.016320,100.119064,106.0,37.0,0.0,1.633897,1.729871
...,...,...,...,...,...,...,...,...,...,...,...,...
9896,20220416,37,37199,18357,10367022,0.001771,41.000000,76.0,51.0,0.0,0.072599,0.134574
9897,20220423,37,37199,18357,10367022,0.001771,60.000000,29.0,51.0,0.0,0.106243,0.051351
9898,20220430,37,37199,18357,10367022,0.001771,33.000000,42.0,51.0,0.0,0.058433,0.074370
9899,20220507,37,37199,18357,10367022,0.001771,33.000000,1172.0,57.0,6.0,0.058433,2.075273

### <font color=blue> Add time-varying variable: true_county_inc_deaths from t-4 to t-11 weeks.

In [104]:
from epsampling.data_processing import add_death_history_cols
df_tot = add_death_history_cols(df, target_col='True_county_inc_deaths')

with pd.option_context('display.min_rows', 20):
    display(df_tot)

100%|██████████| 100/100 [00:11<00:00,  8.79it/s]

,Date,State_fips,Fips,Pop,State_pop,Ratio,Proj_state_inc_deaths,True_state_inc_deaths,True_county_cum_deaths,True_county_inc_deaths,Naive_proj_deaths,Naive_true_deaths,True_county_inc_deaths_tm_4,True_county_inc_deaths_tm_5,True_county_inc_deaths_tm_6,True_county_inc_deaths_tm_7,True_county_inc_deaths_tm_8,True_county_inc_deaths_tm_9,True_county_inc_deaths_tm_10,True_county_inc_deaths_tm_11
0,20200620,37,37001,169185,10367022,0.016320,122.952377,104.0,35.0,3.0,2.006526,1.697232,None,None,None,None,None,None,None,None
1,20200627,37,37001,169185,10367022,0.016320,100.308655,95.0,36.0,1.0,1.636991,1.550356,None,None,None,None,None,None,None,None
2,20200704,37,37001,169185,10367022,0.016320,119.399124,80.0,37.0,1.0,1.948538,1.305563,None,None,None,None,None,None,None,None
3,20200711,37,37001,169185,10367022,0.016320,100.119064,106.0,37.0,0.0,1.633897,1.729871,None,None,None,None,None,None,None,None
4,20200718,37,37001,169185,10367022,0.016320,120.176331,133.0,39.0,2.0,1.961222,2.170498,None,None,None,None,None,None,None,None
5,20200725,37,37001,169185,10367022,0.016320,131.000000,148.0,40.0,1.0,2.137859,2.415291,None,None,None,None,None,None,None,None
6,20200801,37,37001,169185,10367022,0.016320,152.000000,188.0,41.0,1.0,2.480570,3.068073,None,None,None,None,None,None,None,None
7,20200808,37,37001,169185,10367022,0.016320,162.000000,195.0,41.0,0.0,2.643765,3.182310,None,None,None,None,None,None,None,None
8,20200815,37,37001,169185,10367022,0.016320,208.000000,186.0,42.0,1.0,3.394464,3.035434,None,None,None,None,None,None,None,None
9,20200822,37,37001,169185,10367022,0.016320,149.000000,176.0,44.0,2.0,2.431611,2.872239,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9890,20220305,37,37199,18357,10367022,0.001771,332.000000,263.0,51.0,1.0,0.587876,0.465697,3.0,1.0,6.0,1.0,1.0,0.0,0.0,0.0
9891,20220312,37,37199,18357,10367022,0.001771,233.000000,159.0,51.0,0.0,0.412576,0.281543,1.0,3.0,1.0,6.0,1.0,1.0,0.0,0.0
9892,20220319,37,37199,18357,10367022,0.001771,150.000000,136.0,51.0,0.0,0.265607,0.240817,1.0,1.0,3.0,1.0,6.0,1.0,1.0,0.0
9893,20220326,37,37199,18357,10367022,0.001771,127.000000,116.0,51.0,0.0,0.224880,0.205402,0.0,1.0,1.0,3.0,1.0,6.0,1.0,1.0
9894,20220402,37,37199,18357,10367022,0.001771,115.000000,41.0,51.0,0.0,0.203632,0.072599,1.0,0.0,1.0,1.0,3.0,1.0,6.0,1.0
9895,20220409,37,37199,18357,10367022,0.001771,55.000000,43.0,51.0,0.0,0.097389,0.076141,0.0,1.0,0.0,1.0,1.0,3.0,1.0,6.0
9896,20220416,37,37199,18357,10367022,0.001771,41.000000,76.0,51.0,0.0,0.072599,0.134574,0.0,0.0,1.0,0.0,1.0,1.0,3.0,1.0
9897,20220423,37,37199,18357,10367022,0.001771,60.000000,29.0,51.0,0.0,0.106243,0.051351,0.0,0.0,0.0,1.0,0.0,1.0,1.0,3.0
9898,20220430,37,37199,18357,10367022,0.001771,33.000000,42.0,51.0,0.0,0.058433,0.074370,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
9899,20220507,37,37199,18357,10367022,0.001771,33.000000,1172.0,57.0,6.0,0.058433,2.075273,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [98]:
## SAVE CSVs!
fpath = os.path.join(DATA_DIR,'processed',f'training_target_df_{DT}.csv')
df_tot.to_csv(fpath,index=False)
print(DT)

fpath = os.path.join(DATA_DIR,'processed',f'training_acs_df_{DT}.csv')
dff_acs.to_csv(fpath,index=False)
print(DT)

20241108-123515
20241108-123515