In [1]:
%%capture
%load_ext autoreload
%autoreload 2
from setup_nb_env import *

In [2]:
from epsampling.utils import load_latest_csv, get_point_pred_performance

In [3]:
data_dir = '/work/users/k/4/k4thryn/Repos/EpSampling/data'

df,name = load_latest_csv('merged_covs_deaths',f'{data_dir}/processed/')
df.drop('Postal',axis=1,inplace=True)
df.rename({'COVIDhubEns_state_deaths':'State_deaths_ens','True_county_deaths':'County_deaths_true',
           'Naive_county_deaths':'County_deaths_naive'},axis=1,inplace=True)
df

,State_fips,State,County,Fips,Date,State_deaths_ens,Pop,Pop_ratio,County_deaths_true,County_deaths_naive,...,HU_x15,HU_UIS01D,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS0509,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
0,41,OR,Baker,41001,2020-05-09,125.655,16124,0.003823,0.0,0.480367,...,8654,6300,109,162,159,183,105,90,157,1389
1,41,OR,Baker,41001,2020-05-16,143.950,16124,0.003823,0.0,0.550307,...,8654,6300,109,162,159,183,105,90,157,1389
2,41,OR,Baker,41001,2020-05-23,150.378,16124,0.003823,0.0,0.574881,...,8654,6300,109,162,159,183,105,90,157,1389
3,41,OR,Baker,41001,2020-05-30,159.093,16124,0.003823,0.0,0.608197,...,8654,6300,109,162,159,183,105,90,157,1389
4,41,OR,Baker,41001,2020-06-06,164.199,16124,0.003823,0.0,0.627717,...,8654,6300,109,162,159,183,105,90,157,1389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332432,24,MD,Baltimore city,24510,2022-04-09,14367.000,593490,0.098168,1765.0,1410.374156,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332433,24,MD,Baltimore city,24510,2022-04-16,14391.000,593490,0.098168,1771.0,1412.730179,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332434,24,MD,Baltimore city,24510,2022-04-23,14423.000,593490,0.098168,1771.0,1415.871543,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332435,24,MD,Baltimore city,24510,2022-04-30,14443.000,593490,0.098168,1773.0,1417.834895,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332436,24,MD,Baltimore city,24510,2022-05-07,14488.000,593490,0.098168,1776.0,1422.252438,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457

In [4]:
print(
    'Num samples:',len(df),'\n',
    'Num dates:',df.Date.nunique(),'\n',
    'Num counties:',df.Fips.nunique(),'\n',
     )

Num samples: 332437
 Num dates: 107
 Num counties: 3130

In [5]:
acs_covs = df.columns[10:]
death_covs = df.columns[:10]

df_acs = df[acs_covs]
df_deaths = df[death_covs]

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


y_naive = df['County_deaths_naive']
y_test = df['County_deaths_true']
# y_pred = df['']


def get_point_pred_performance(model_names, model_preds, my_metrics):
    
    if len(model_names) != len(model_preds):
        raise Exception as e:
            return "Num model names doesn't match num model preds!"
    
    if len(model_preds)==1:
        model_preds = [model_preds]
        model_names = [model_names]
    
    all_metrics = ['MAE','MSE','r2']
    
    model_res_dict = {model:{} for model in model_names}
    
    for name,pred in zip(model_names, model_preds):
        
        model_res_dict[name] = {}
        
        for metric in all_metrics:
            if metric not in my_metics:
                continue
            
        for metric in metrics:
        metrics = {}
        mae = mean_absolute_error(y_test, pred)
        mse = mean_squared_error(y_test, pred)
        r2 = r2_score(y_test, pred)
        
        metrics
        print(mae, mse, r2)

In [ ]:
y_naive = df['County_deaths_naive'].values
y_test = df['County_deaths_true'].values

model_names = ['County_deaths_naive','County_deaths_true']
model_preds = y_naive, y_test

import pprint
pprint.pp(get_point_pred_performance(model_names, model_preds, y_test))

how to make dictionary from key to function?

In [ ]:
import pprint

In [6]:
y_naive = df['County_deaths_naive'].values
y_test = df['County_deaths_true'].values

model_names = ['County_deaths_naive','County_deaths_true']
model_preds = y_naive, y_test

import pprint
pprint.pp(get_point_pred_performance(model_names, model_preds, y_test))

{'County_deaths_naive': {'MAE': 45.12020251173903,
                         'MSE': 32283.266378723525,
                         'r2': 0.9174753744784435},
 'County_deaths_true': {'MAE': 0.0, 'MSE': 0.0, 'r2': 1.0}}