In [1]:
import pandas as pd
import numpy as np
import csv
from tqdm import tqdm
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

d = datetime.today().strftime('%Y%m%d-%H%M%S')
data_dir = '/work/users/k/4/k4thryn/Repos/EpSampling/data'

import glob
def get_latest(csv_name, data_dir=f'{data_dir}/processed/'):
#     csv_name = 'all_county_acs_covs'
    dates = sorted([x[-19:-4] for x in glob.glob(f'{data_dir}{csv_name}*')])
    latest = dates[-1]
    file_name = f'{data_dir}{csv_name}_{latest}.csv'
    return file_name

In [2]:
# print(get_latest('all_county_acs_covs',f'{data_dir}/processed/'))

csv = get_latest('merged_covs_deaths',f'{data_dir}/processed/')
_df = pd.read_csv(csv)

acs_covs = list(_df.columns[11:].values)
death_covs = ['Fips','Date','COVIDhubEns_state_deaths', 'Pop', 'Pop_ratio','Naive_county_deaths']
target = ['True_county_deaths']

all_covs = target + death_covs + acs_covs
df = _df[all_covs]

In [3]:
def time_to_int(date):
    y,m,d = date.split('-')
    total = 0
    total += int(d) * 60 
    total += (int(m) - 1) * 60 * 60 
    total += (int(y) - 1970) * 60 * 60 * 24
    return total
    print(y,m,d)
    return 10*y + 100*m + d

df['Date'] = df.Date.apply(lambda x: time_to_int(x))
df = df.dropna(how='any',axis=1)
df

,True_county_deaths,Fips,Date,COVIDhubEns_state_deaths,Pop,Pop_ratio,Naive_county_deaths,POP_x2,POP_M,POP_F,...,HU_x15,HU_UIS01D,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS0509,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
0,0.0,41001,4334940,125.655,16124,0.003823,0.480367,16539,8458,8081,...,8654,6300,109,162,159,183,105,90,157,1389
1,0.0,41001,4335360,143.950,16124,0.003823,0.550307,16539,8458,8081,...,8654,6300,109,162,159,183,105,90,157,1389
2,0.0,41001,4335780,150.378,16124,0.003823,0.574881,16539,8458,8081,...,8654,6300,109,162,159,183,105,90,157,1389
3,0.0,41001,4336200,159.093,16124,0.003823,0.608197,16539,8458,8081,...,8654,6300,109,162,159,183,105,90,157,1389
4,0.0,41001,4338360,164.199,16124,0.003823,0.627717,16539,8458,8081,...,8654,6300,109,162,159,183,105,90,157,1389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332432,1765.0,24510,4504140,14367.000,593490,0.098168,1410.374156,592211,278792,313419,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332433,1771.0,24510,4504560,14391.000,593490,0.098168,1412.730179,592211,278792,313419,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332434,1771.0,24510,4504980,14423.000,593490,0.098168,1415.871543,592211,278792,313419,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332435,1773.0,24510,4505400,14443.000,593490,0.098168,1417.834895,592211,278792,313419,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457
332436,1776.0,24510,4507620,14488.000,593490,0.098168,1422.252438,592211,278792,313419,...,293718,43042,149324,14615,16871,17300,12674,7999,31436,457

In [4]:
## Remove highly correlated features.

corr_thresh = 0.97

corr_matrix = df.corr().abs()
## Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
## Find features with correlation greater than like .99 ...
to_drop = [column for column in upper.columns if any(upper[column] > corr_thresh)]
## Drop features 
df_filt = df.drop(to_drop, axis=1, inplace=False)
df_filt

,True_county_deaths,Fips,Date,COVIDhubEns_state_deaths,Pop,Pop_ratio,Naive_county_deaths,EDU_ltHS,EDU_DOCT,IND_AFFHM,...,POP_NHPINH,POP_OTH2PLNH,POP_AIAN,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
0,0.0,41001,4334940,125.655,16124,0.003823,0.480367,1130,77,639,...,32,412,235,109,162,159,105,90,157,1389
1,0.0,41001,4335360,143.950,16124,0.003823,0.550307,1130,77,639,...,32,412,235,109,162,159,105,90,157,1389
2,0.0,41001,4335780,150.378,16124,0.003823,0.574881,1130,77,639,...,32,412,235,109,162,159,105,90,157,1389
3,0.0,41001,4336200,159.093,16124,0.003823,0.608197,1130,77,639,...,32,412,235,109,162,159,105,90,157,1389
4,0.0,41001,4338360,164.199,16124,0.003823,0.627717,1130,77,639,...,32,412,235,109,162,159,105,90,157,1389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332432,1765.0,24510,4504140,14367.000,593490,0.098168,1410.374156,56716,10519,638,...,131,19989,1706,149324,14615,16871,12674,7999,31436,457
332433,1771.0,24510,4504560,14391.000,593490,0.098168,1412.730179,56716,10519,638,...,131,19989,1706,149324,14615,16871,12674,7999,31436,457
332434,1771.0,24510,4504980,14423.000,593490,0.098168,1415.871543,56716,10519,638,...,131,19989,1706,149324,14615,16871,12674,7999,31436,457
332435,1773.0,24510,4505400,14443.000,593490,0.098168,1417.834895,56716,10519,638,...,131,19989,1706,149324,14615,16871,12674,7999,31436,457
332436,1776.0,24510,4507620,14488.000,593490,0.098168,1422.252438,56716,10519,638,...,131,19989,1706,149324,14615,16871,12674,7999,31436,457

In [15]:
df_filt = df_filt.sample(n=50000)
df_filt

,True_county_deaths,Fips,Date,COVIDhubEns_state_deaths,Pop,Pop_ratio,Naive_county_deaths,POP_A1819,EDU_ltHS,EDU_ASSOC,...,POP_OTH2PL,HU_UIS01D,HU_UIS01A,HU_UIS02,HU_UIS0304,HU_UIS0509,HU_UIS1019,HU_UIS2049,HU_UIS50P,HU_UISOTHER
324434,143.0,8035,4360320,3684.000,351154,0.060978,224.641542,8642,5012,18060,...,25086,99213,7606,295,2003,5185,6628,5026,6169,394
128002,24.0,53001,4428180,5964.000,19983,0.002624,15.650727,568,3489,760,...,8626,3966,186,260,142,143,90,150,45,1714
220481,46.0,30041,4429440,1703.000,16484,0.015423,26.265746,443,893,962,...,931,5434,167,182,252,171,99,25,61,842
5631,69.0,25015,4335360,5780.674,160830,0.023334,134.886528,14446,4744,8860,...,10807,39634,3708,5880,5814,3647,2455,2346,1575,725
117640,8.0,20055,4336200,220.928,36467,0.012517,2.765435,1235,6388,1757,...,7553,9019,329,395,1246,502,406,191,61,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207972,1.0,5121,4339200,206.209,17958,0.005951,1.227085,410,1821,1150,...,1188,6758,106,298,193,22,43,48,9,1095
186568,112.0,13091,4433280,22471.000,20605,0.001941,43.608977,493,2045,953,...,470,5134,99,106,389,254,37,28,0,2617
28965,31.0,1107,4407360,5639.000,19930,0.004065,22.920871,463,2332,1012,...,496,5719,48,273,311,149,68,47,4,2119
183246,149.0,13059,4429440,21628.000,128331,0.012087,261.413986,11428,7515,4805,...,9744,26077,3421,3530,3638,4114,5768,2774,3041,2725
110881,79.0,28091,4418640,7193.000,24573,0.008257,59.390034,531,2749,2121,...,601,7739,59,48,253,66,36,235,24,2721

In [5]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df_filt, test_size=0.05, random_state=666)
target = 'True_county_deaths'

covs_to_drop = [target, 
                    # 'Fips','Naive_county_deaths','Pred_state_deaths'
               ]

X_train = df_train.drop(covs_to_drop,axis=1)
y_train = df_train[target].values
X_test = df_test.drop(covs_to_drop,axis=1)
y_test = df_test[target].values

y_naive = df_test['Naive_county_deaths'].values

print(len(X_train), len(X_test))


from sklearn.ensemble import RandomForestRegressor

clf = RandomForestRegressor(random_state=666, max_depth=6)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test) #[:,None]
# y_prob = clf.predict_proba(X_test)[:,0]

# y_naive = X_test['Naive_county_deaths'].values

# print(y_test[:10])
# print(y_pred[:10])
# print(y_naive[:10])

315815 16622

In [6]:
y_pred

array([517.38126962,   5.48194901,   5.48194901, ..., 513.85070637,
       197.34250942, 156.19886653])

In [7]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

for pred in [y_naive, y_pred]:
    mae = mean_absolute_error(y_test, pred)
    mse = mean_squared_error(y_test, pred)
    r2 = r2_score(y_test, pred)
    print(mae, mse, r2)

46.6631784780179 34430.81461011078 0.9205246142114295
37.356749479467894 9744.053548397995 0.9775081587911078

In [ ]:
# # from IPython.display import Audio, display
# import IPython

# def allDone():
# #     urL = 'https://www.wavsource.com/snds_2020-10-01_3728627494378403/animals/cat_meow2.wav'
# #     urL = 'https://www.wavsource.com/snds_2020-10-01_3728627494378403/animals/cat_meow2.wav'
# #     display(Audio(url=urL, autoplay=True))
    
#     IPython.display.Audio('../cat_meow2.wav',autoplay=True)
# allDone()